# Generated by Django 4.2.3 on 2023-07-11 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_intrusionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="intrusionimage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
