name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.17
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.17

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Flake8 linting
      run: |
        pip install flake8
        flake8 .
    
    - name: Run pylint code analysis
      run: |
        pip install pylint pylint-django
        pylint --load-plugins pylint_django .
        
